version: "1"
services:
  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    networks:
      - ollama-docker
  rag-hpc-server:
    restart: "no"
    container_name: rag-hpc-server
    volumes:
      - .:/app
    image: rag-hpc-server
    ports:
      - 5001:3001
    build:
      context: .
    networks:
      - ollama-docker
    depends_on:
      - ollama

networks:
  ollama-docker:
    driver: bridge