version: "1"
services:
  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434

  rag-hpc-server:
    restart: always 
    container_name: rag-hpc-server
    image: rag-hpc-server
    ports:
      - 5001:3001
    build:
      context: . 